name: Serverhost
version: '3.1.2'
main: de.fynn.webserver.WebServerPlugin
api-version: '1.21'
folia-supported: false
description: Leichtgewichtiger HTTP-Webserver fuer statische Dateien
authors: [Fynn]

commands:
  webserver:
    description: WebServer Verwaltung
    usage: /<command> [reload|status|start|stop|stats|analytics|gui|check|resetstats|debug|overview|log]
    permission: webserver.admin

permissions:
  webserver.admin:
    description: Erlaubt die Verwaltung des Webservers
    default: op
